name = "ramznewsofficial"
main = "src/index.js"
compatibility_date = "2023-11-01"
nodejs_compat = true

# Set up KV namespace for tracking posts
kv_namespaces = [
  { binding = "POST_TRACKER", id = "6275727dfdcf4de29088dba0313e6dcc" }
]

[triggers]
# Run every 30 minutes
crons = ["*/30 * * * *"] 