name = "ramznewsofficial"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
# Run every 30 minutes
crons = ["*/30 * * * *"] 

# KV namespace configuration
[[kv_namespaces]]
binding = "POST_TRACKER"
id = "6275727dfdcf4de29088dba0313e6dcc"
