name = "ramznewsofficial"
main = "src/index.js"
compatibility_date = "2023-11-01"
node_compat = true

# Set up KV namespace for tracking posts
kv_namespaces = [
  { binding = "POST_TRACKER", id = "فقط شناسه KV namespace را که از داشبورد کلادفلر کپی کرده‌اید اینجا قرار دهید" }
]

[triggers]
# Run every 30 minutes
crons = ["*/30 * * * *"] 